site_name: MJ-Ahmad Documentation Hub
site_description: Ethical Governance, Financial Sovereignty, and Inheritable Automation
site_author: MJ Ahmad — Steward of Ethical Inheritance
repo_url: https://github.com/mj-ahmad/mj-ahmad
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo1.jpg
  favicon: assets/logo1.jpg
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Core Modules:
      - Overview: core-overview.md
      - Constitution: constitution.md
      - Whitepaper: whitepaper.md
      - Glossary: glossary.md
      - Roadmap: roadmap.md
      - Contributors: contributors.md
      - Contributing: CONTRIBUTING.md

  - Logic & Ethics:
      - Overview: logic-ethics-overview.md
      - NXN Genesis: nxn-genesis/README.md
      - Rules: nxn-genesis/rules.md
      - NXN Ethics: nxn-ethics/README.md
      - Violation: nxn-ethics/violations.md
      - Manifesto: ethics.md
  - Governance:
      - Overview: governance-overview.md
      - Community Charter: governance/community-charter.md
      - Role Activation: governance/role-activation.md
      - Visionary Roles: governance/visionary-roles.md
      - Audit Log Policy: governance/audit-policy.md
      - Review Protocol: governance/review-protocol.md
      - Proposal Template: governance/proposal-template.md
      - Decision Tree: governance/decision-tree.md
      - Voting Policy: governance/voting-policy.md
      - Emergency Protocol: governance/emergency-protocol.md
      - Ratification Process: governance/ratification-process.md
      - Ratified Actions: governance/ratified-actions.md
  - Behavioral Governance:
      - Overview: behavior-overview.md
      - Persona Consistency: behavior/persona-consistency.md
  - Security:
      - Overview: security-overview.md
      - Threat Model: security/threat-model.md
      - Incident Response: security/incident-response.md
      - Guardian Handbook: security/guardian-handbook.md
  - Treasury:
      - Overview: treasury-overview.md
      - Treasury: treasury/README.md
      - Purpose Registry: treasury/purpose-registry.md
      - Disbursement Log: treasury/disbursement-log.md
  - Merit:
      - Overview: merit-overview.md
      - Merit System: merit-engine/README.md
      - Scorecard: merit-engine/scorecard.md
  - Distribution:
      - Overview: distribution-overview.md
      - Distribution Engine: distribution-engine/README.md
  - Deployment:
      - Overview: deployment-overview.md
      - Deployment Guide: deployment-guide.md
      - Deployment Record: deployment-record.md
  - Tokenomics:
      - Overview: tokenomics-overview.md
      - Tokenomics: tokenomics.md
  - Quraner Fariwala:
      - Overview: quraner-fariwala-overview.md
      - Module Summary: quraner-fariwala/README.md
      - Public Index: quraner-fariwala/quraner-fariwala-index.md
      - Research & Ethics:
          - Research Methodology: quraner-fariwala/research.md
          - Interpretive Boundaries: quraner-fariwala/ethics.md
          - Distribution Ethics: quraner-fariwala/distribution.md
      - Legal Continuity:
          - Declaration: quraner-fariwala/quraner-fariwala-legal-continuity.md
          - BD Renewal Letter: quraner-fariwala/legal-correspondence/trade-license-renewal-request.md
          - UK Reinstatement Letter: quraner-fariwala/legal-correspondence/uk-reinstatement-request.md
      - Restoration & Campaign:
          - Restoration Plan: quraner-fariwala/quraner-fariwala-restoration-plan.md
          - Campaign Manifesto: quraner-fariwala/quraner-fariwala-campaign-manifesto.md
          - Sponsorship Tiers: quraner-fariwala/sponsor-tiers.md
          - Sponsor Badges: quraner-fariwala/sponsor-badges/sponsor.md
      - Donation Gateway: quraner-fariwala/quraner-fariwala-donation-gateway.md
  - Stewardship & Finance:
      - Personal Fund Declaration: personal-fund-declaration.md
      - Personal Fund Log: personal-fund-log.md
      - Support MJ Ahmad: support-mj.md
      - Verified Bank Accounts: bank-accounts.md
  - Audit & Metadata:
      - Audit Log: audit/change-log.json
  - Support & Clarity:
      - Overview: support-overview.md
      - FAQ: faq.md
      - Vision: vision.md
  - LifeFuel:
      - 🏛️ Overview:
          - Welcome: LifeFuel/index.md
          - Roadmap: LifeFuel/roadmap.md
          - Timeline: LifeFuel/Timeline.md
          - Keywords: LifeFuel/Learnings/Keywords.md
      - 🧭 Initiation Layer:
          - Task Manager: LifeFuel/Initiation/SDF-INIT-01.md
          - Performance Monitor: LifeFuel/Initiation/SDF-INIT-02.md
          - Event Viewer: LifeFuel/Initiation/SDF-INIT-03.md
          - Sysinternals Tools: LifeFuel/Initiation/SDF-INIT-04.md
          - PowerShell Basics: LifeFuel/Initiation/SDF-INIT-05.md
      - 📊 Observation Layer:
          - get-process.ps1: LifeFuel/Observation/SDF-OBS-01.md
          - get-service.ps1: LifeFuel/Observation/SDF-OBS-02.md
          - get-eventlog.ps1: LifeFuel/Observation/SDF-OBS-03.md
          - get-counter.ps1: LifeFuel/Observation/SDF-OBS-04.md
          - get-osinfo.ps1: LifeFuel/Observation/SDF-OBS-05.md
      - 📜 Reporting Layer:
          - Export-Csv: LifeFuel/Reporting/SDF-REP-01.md
          - Out-File: LifeFuel/Reporting/SDF-REP-02.md
          - Markdown Template: LifeFuel/Reporting/SDF-REP-03.md
          - ConvertTo-Json: LifeFuel/Reporting/SDF-REP-04.md
          - Send-MailMessage: LifeFuel/Reporting/SDF-REP-05.md
      - 📁 Documentation Layer:
          - Daily Logs: LifeFuel/Logs/index.md
          - Performance Reports: LifeFuel/Reports/Performance/index.md
          - Timeline: LifeFuel/Timeline.md
          - Keywords: LifeFuel/Learnings/Keywords.md
      - 🧠 Mastery Layer:
          - Write Custom Scripts: LifeFuel/Mastery/SDF-MAS-01.md
          - Create Markdown Guides: LifeFuel/Mastery/SDF-MAS-02.md
          - Publish on GitHub: LifeFuel/Mastery/SDF-MAS-03.md
          - Campaign Summary: LifeFuel/Mastery/SDF-MAS-04.md
      - 🧾 Featured Project:
          - Quraner Fariwala: LifeFuel/projects/quran-fariwala-40k/index.md
      - 🧰 System Roles:
          - Microsoft Copilot: LifeFuel/Roles/Copilot.md
          - PowerShell: LifeFuel/Roles/PowerShell.md
          - Python: LifeFuel/Roles/Python.md
          - GitHub Actions: LifeFuel/Roles/GitHubActions.md
          - MkDocs: LifeFuel/Roles/MkDocs.md
          - GitBook: LifeFuel/Roles/GitBook.md
          - GitHub Pages: LifeFuel/Roles/GitHubPages.md
          - Markdown: LifeFuel/Roles/Markdown.md
          - Microsoft Trust Framework: LifeFuel/Roles/TrustFramework.md
      - ✅ Audit Log:
          - Audit Entries: LifeFuel/AuditLog/index.md
      - 📚 Learning Protocol:
          - Update Rules: LifeFuel/protocol/update.md
          - Class & Quiz Setup: LifeFuel/protocol/learning-structure.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-ahmad


