site_name: MJ-Ahmad Documentation Hub
site_description: Ethical Governance, Financial Sovereignty, and Inheritable Automation
site_author: MJ Ahmad — Steward of Ethical Inheritance
repo_url: https://github.com/mj-ahmad/mj-ahmad
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo1.jpg
  favicon: assets/logo1.jpg
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Constitution: constitution.md
  - Whitepaper: whitepaper.md
  - Roadmap: roadmap.md
  - Glossary: glossary.md
  - Governance:
      - Visionary Roles: governance/visionary-roles.md
      - Persona Consistency: behavior/persona-consistency.md
      - Proposal Template: governance/proposal-template.md
      - Decision Tree: governance/decision-tree.md
      - Voting Policy: governance/voting-policy.md
      - Emergency Protocol: governance/emergency-protocol.md
      - Ratification Process: governance/ratification-process.md
      - Ratified Actions: governance/ratified-actions.md
  - Treasury:
      - Treasury Policy: nexara-treasury/README.md
      - Purpose Registry: treasury/purpose-registry.md
      - Disbursement Log: treasury/disbursement-log.md
  - Merit System: merit-engine/README.md
  - Deployment:
      - Deployment Guide: deployment-guide.md
      - Deployment Record: deployment-record.md
  - Tokenomics: tokenomics.md
  - Security:
      - Threat Model: security/threat-model.md
      - Audit Log Policy: audit-policy.md
      - Incident Response: security/incident-response.md
      - Guardian Handbook: security/guardian-handbook.md
  - Quraner Fariwala:
      - Research Overview: quraner-fariwala/research.md
      - Distribution Ethics: quraner-fariwala/distribution.md
      - Interpretive Boundaries: quraner-fariwala/ethics.md
  - Ethics Manifesto: ethics.md
  - Community:
      - Community Charter: community-charter.md
      - FAQ: faq.md
  - Contributing: CONTRIBUTING.md
  - Vision: vision.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-ahmad


