site_name: MJ-Ahmad Documentation Hub
site_description: Ethical Governance, Financial Sovereignty, and Inheritable Automation
site_author: MJ Ahmad — Steward of Ethical Inheritance
repo_url: https://github.com/mj-ahmad/mj-ahmad
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo1.jpg
  favicon: assets/logo1.jpg
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Core Modules:
      - Overview: core-overview.md
      - Constitution: constitution.md
      - Whitepaper: whitepaper.md
      - Glossary: glossary.md
      - Roadmap: roadmap.md
      - Contributors: contributors.md
      - Contributing: CONTRIBUTING.md

  - Logic & Ethics:
      - Overview: logic-ethics-overview.md
      - NXN Genesis: nxn-genesis/README.md
      - Rules: nxn-genesis/rules.md
      - NXN Ethics: nxn-ethics/README.md
      - Violation: nxn-ethics/violations.md
      - Manifesto: ethics.md
  - Governance:
      - Overview: governance-overview.md
      - Community Charter: governance/community-charter.md
      - Role Activation: governance/role-activation.md
      - Visionary Roles: governance/visionary-roles.md
      - Audit Log Policy: governance/audit-policy.md
      - Review Protocol: governance/review-protocol.md
      - Proposal Template: governance/proposal-template.md
      - Decision Tree: governance/decision-tree.md
      - Voting Policy: governance/voting-policy.md
      - Emergency Protocol: governance/emergency-protocol.md
      - Ratification Process: governance/ratification-process.md
      - Ratified Actions: governance/ratified-actions.md
  - Behavioral Governance:
      - Overview: behavior-overview.md
      - Persona Consistency: behavior/persona-consistency.md
  - Security:
      - Overview: security-overview.md
      - Threat Model: security/threat-model.md
      - Incident Response: security/incident-response.md
      - Guardian Handbook: security/guardian-handbook.md
  - Treasury:
      - Overview: treasury-overview.md
      - Treasury: treasury/README.md
      - Purpose Registry: treasury/purpose-registry.md
      - Disbursement Log: treasury/disbursement-log.md
  - Merit:
      - Overview: merit-overview.md
      - Merit System: merit-engine/README.md
      - Scorecard: merit-engine/scorecard.md
  - Distribution:
      - Overview: distribution-overview.md
      - Distribution Engine: distribution-engine/README.md
  - Deployment:
      - Overview: deployment-overview.md
      - Deployment Guide: deployment-guide.md
      - Deployment Record: deployment-record.md
  - Tokenomics:
      - Overview: tokenomics-overview.md
      - Tokenomics: tokenomics.md
  - Quraner Fariwala:
      - Overview: quraner-fariwala-overview.md
      - Quraner Fariwala: quraner-fariwala/README.md
      - Research Overview: quraner-fariwala/research.md
      - Interpretive Boundaries: quraner-fariwala/ethics.md
      - Distribution Ethics: quraner-fariwala/distribution.md
  - Support & Clarity:
      - Overview: support-overview.md
      - FAQ: faq.md
      - Vision: vision.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-ahmad


