<#
.SYNOPSIS
Collects audit entries from all systems and updates metadata/audit-log.md

.DESCRIPTION
Scans DonorSystem, SupporterSystem, ReceiptSystem, and PaymentSystem for changes.
Generates timestamped entries and appends to audit-log.md in metadata folder.
#>

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
$logPath = "metadata/audit-log.md"

$systems = @("DonorSystem", "SupporterSystem", "ReceiptSystem", "PaymentSystem")
foreach ($system in $systems) {
    $files = Get-ChildItem "systems/$system" -Recurse -Include *.json, *.md
    foreach ($file in $files) {
        $entry = @"
## $timestamp
- Action: Scanned $($file.Name)
- File: $($file.FullName)
- Steward Note: Audit entry generated by audit.ps1
"@
        Add-Content -Path $logPath -Value $entry
    }
}
Write-Host "✅ Audit log updated at $timestamp"

